## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

title = "Title"
theme = "hyde-hyde"

## Social Accounts
[params.social]
    github = "nemotoy"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about"
